fix: `draw_graph` raises more informative error for empty external functions (#2559)
**Context:**

Due to a poorly written function, `draw_graph` crashed and burned on
`gridsynth` without a helpful error message. This is due `draw_graph`'s
lack of support for empty function calls. See
https://github.com/PennyLaneAI/catalyst/issues/2541 for more details.

**Description of the Change:**

Add a better guard against external functions that have no body.

**Benefits:** Better error messaging.

Now you get,

```python
import pennylane as qml
from catalyst import *

null_dev = qml.device("null.qubit", wires=1)

@qjit
@qml.transforms.gridsynth
@qml.qnode(null_dev)
def circuit():
    qml.RZ(0.1, 0)
    return qml.probs()

>>> draw_graph(circuit, level=1)()
VisualizationError: Empty function calls are not yet compatible with 'draw_graph'. Found external function call to rs_decomposition_get_phase.
```

**Possible Drawbacks:** Doesn't actually add the feature.

**Related GitHub Issues:**
https://github.com/PennyLaneAI/catalyst/issues/2541
[sc-113503]

---------

Co-authored-by: Mudit Pandey <18223836+mudit2812@users.noreply.github.com>
Co-authored-by: David Ittah <dime10@users.noreply.github.com>