Add error if transform applied inside a qnode with program capture. (#2256)
**Context:**

We currently don't support applying transforms to a subcircuit. We need
to explicitly error out on this case.

For:
```
@qml.qjit
@qml.qnode(qml.device('lightning.qubit', wires=1))
@qml.transforms.cancel_inverses
def c():
    qml.X(0)
    qml.X(0)
    return qml.probs()

c(), print(c.mlir)
```
we would have gotten:
```
TypeError: No ir_type_handler for aval type: <class 'pennylane.measurements.capture_measurements._get_abstract_measurement.<locals>.AbstractMeasurement'>
```

Now we get:
```
NotImplementedError: transforms cannot currently be applied inside a QNode.
```
Which is much more helpful and informative.

**Description of the Change:**

`QFuncToPlxprInterpreter` now raises an error if it encounters a
transform.

**Benefits:**

Improved usability.

**Possible Drawbacks:**

**Related GitHub Issues:**

[sc-104320]