Fix missing import in OpenQASM runtime backend (#1324)
On mac the runtime build fails with:
```
/catalyst/runtime/lib/backend/openqasm/openqasm_python_module.cpp:162:20: error: no member named 'pow' in namespace 'std'; did you mean simply 'pow'?
  162 |     probs->reserve(std::pow(2, num_qubits));
```