Fix subobject linkage
Resolves the issue where a member type was declared in an anonymous
namespace:

  error: ‘catalyst::ion::OQDDatabaseManager’ has a field ‘std::vector<{anonymous}::Beam> whose type has internal linkage [-Werror=subobject-linkage]
    29 | class OQDDatabaseManager {