fix: update `get_mlir_module` to no longer use the xDSL pass plugin (#2303)
Bug occured due to this helper function still relying on the xDSL pass
plugin,
```python
from catalyst.python_interface.inspection.specs import mlir_specs

dev = qml.device("lightning.qubit", wires=1)

@qml.qjit
@qml.qnode(dev)
def my_workflow(x):
    qml.X(0)
    
>>> mlir_specs(my_workflow, 0, 1)
CompileError: catalyst failed with error code -6: Assertion failed: (!resAttrDicts.empty() && "expected array to be non-empty"), function convertFuncOpToLLVMFuncOp, file FuncToLLVM.cpp, line 386.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace and instructions to reproduce the bug.
```

[sc-105948]

---------

Co-authored-by: Mudit Pandey <18223836+mudit2812@users.noreply.github.com>