refactor: all passes in `builtin_passes.py` are now `Transform` objects (#2722)
**Context:**

Right now, we can't do this,
```python
>>> from catalyst.passes import to_ppr
>>> import pennylane as qp
>>> qp.CompilePipeline(to_ppr)
TypeError: CompilePipeline can only be constructed with a series of transforms or compile pipelines, or with a single list of transforms.
```

because these passes (although act like `Transform` objects), are not
true `Transform` objects.

**Description of the Change:**

- Instead of defining them as decorators, they are now true `Transform`
objects.
- Added a testing file for these passes where we assert that they are
`Transform` objects.

**Benefits:** Behave truly as `Transform` objects. 

**Possible Drawbacks:** 

- In the
[render](https://xanaduai-pennylane--2722.com.readthedocs.build/projects/catalyst/en/2722/code/__init__.html#module-catalyst-passes),
passes no longer have a link to their source code. This isn't that
alarming as these transforms, when viewed from PennyLane docs, also
don't have a source code link. This is simply due to the implementation
of docstrings being attached to the pass' setup inputs function.
- Users must manually remember to add their new pass to `__all__` or
else it won't render on the website.
- IDEs can't pick up the docstring or the signature of these objects

Fixes #2766 

[sc-117354] [sc-118014]

---------

Co-authored-by: River McCubbin <river.mccubbin@xanadu.ai>