Fix config for wheels. (#611)
**Context:** We use different versions of toml depending on which
version of python is running. The tomllib library which we use for
Python 3.11 and Python 3.12 specifies that in order to load a toml file
it must be read in binary mode.

**Description of the Change:** Change the flags to open to binary mode.

**Benefits:** Toml works for wheels of all versions.

**Possible Drawbacks:** None.

**Related GitHub Issues:**

See wheel testing errors

```
FAILED frontend/test/pytest/test_config_functions.py::test_validate_config_with_device[1] - TypeError: File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`
```

since
[here](https://github.com/PennyLaneAI/catalyst/actions/runs/8270528619/job/22628713441)