Use inspect module to get argument counts (#1151)
Using `qml.cond` on PennyLane operators raises an exception because the
target does not have a `__code__` attribute:
```py
@qjit
@qml.qnode(qml.device("lightning.qubit", wires=1))
def f(x: int):
    qml.cond(x < 5, qml.Hadamard)(0)
    return qml.probs()
```
```
AttributeError: type object 'Hadamard' has no attribute '__code__'
```

[sc-74292]