Allow standard `qml.cond` usage of `qml.cond(pred, qml.some_gate)(*args, **kwargs)` in qjit (#1232)
**Context:**
The standard `qml.cond` usage for single gates fails with qjit:
```python
@qjit
@qml.qnode(dev)
def func(x, y):
    qml.cond(x == 42, qml.Hadamard)(wires=0)
    qml.cond(y == 37, qml.Hadamard)(wires=0)
    return qml.probs()

print(func(42, 37), func(42, 2))
```

```
TypeError: Conditional 'True' function is not allowed to have any arguments
```

While users can work around this by using [`catalyst.cond`
syntax](https://docs.pennylane.ai/projects/catalyst/en/stable/code/api/catalyst.cond.html),
it is a bit incovenient.

Moreover, the fewer code changes required to qjit a pennylane circuit,
the better. Since [`qml.cond` just aliases to `catalyst.cond` within
qjit](https://github.com/PennyLaneAI/catalyst/blob/175cf8c3fc04691f74e089506b29cdbc7caa6c14/doc/releases/changelog-0.4.0.md?plain=1#L41),
we should make sure qjit does not reject any valid plain pennylane use
patterns.


**Description of the Change:**
The error arises because the conditional branch functions are not
allowed to have arguments. This is because the `CondCallable` class's
`__call__()` method does not take any arguments.

While we do not want to change the overarching design of `CondCallable`,
we can make a new class that inherits from it, which specifically deals
with the case where the conditional branch function is a pennylane gate
(like `qml.Hadamard`, ...).

This new class, named `CondCallableSingleGateHandler`, has a
`__call__()` method that can take in arbitrary args and kwargs. The
class creates a wrapper conditional function taking in no arguments and
sends the wrapper to the usual `CondCallable`, but the body of the
wrapper calls the actual conditional branch function that is passed in.
This allows us to perform the conditional branch function with
arguments.


**Benefits:**
The standard usage `qml.cond(predicate, qml.some_gate)(*args, **kwargs)`
works within qjit.

**Related GitHub Issues:** closes #449 

[sc-55079]