Update some tests to use jnp.allclose instead of `==` (#1847)
**Context:**
A test is mysteriously failing on ARM machines:
https://github.com/PennyLaneAI/catalyst/actions/runs/16077576091/job/45378065361#step:12:178

```
FAILED frontend/test/pytest/test_capture_integration.py::TestCapture::test_transform_single_qubit_fusion_workflow[lightning.qubit] - assert Array(-0.50022394, dtype=float64) == Array(-0.50022394, dtype=float64)
```

The results do look the same. The leading theory is it's a floating
point error.

**Description of the Change:**
Change to `jax.numpy.allclose`.