update wires for HybridOp (#1676)
**Context:**


In my PR where I can the default `Operator.num_wires = None`:
https://github.com/PennyLaneAI/pennylane/pull/7312

I get failing CI:


https://github.com/PennyLaneAI/pennylane/actions/runs/14602060847/job/40962850893?pr=7312

with errors:
```
TypeError: Must specify a set of wires. None is not a valid wire label.
```

Instead of having a wire label that is `Operator.num_wires`, I'm just
giving `HybridOp` empty wires.

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

[sc-89159]