Fix ODR violation in OQD device tests
Resolves the following error (due to inclusion of a source file
instead of a header file):

  ERROR: AddressSanitizer: odr-violation
    [1] size=37 'typeinfo name for Catalyst::Runtime::Device::OQDDevice' /home/davidi/catalyst/runtime/tests/Test_OQDDevice.cpp
    [2] size=37 'typeinfo name for Catalyst::Runtime::Device::OQDDevice' /home/davidi/catalyst/runtime/lib/backend/oqd/OQDDevice.cpp