Fixing ```Batching rule for 'gather' not implemented``` for jax.scipy.linalg.expm under qml.qjit. (#733)
**Context:** Bug fix:
```python
@qml.qjit
def f(x):
    return jax.scipy.linalg.expm(-2.0 * x)

>>> f(jnp.array([[0.1, 0.2], [5.3, 1.2]]))
[/usr/local/lib/python3.10/dist-packages/jax/_src/interpreters/batching.py](https://localhost:8080/#) in get_primitive_batcher(self, primitive, frame)
    395       return self.get_axis_primitive_batcher(primitive, frame)
    396     msg = "Batching rule for '{}' not implemented"
--> 397     raise NotImplementedError(msg.format(primitive))
    398 
    399   def get_axis_primitive_batcher(self, primitive, frame):

NotImplementedError: Batching rule for 'gather' not implemented
```


Note: the expm bug actually consists of two independent bugs. The first
one, "batching rule for gather not implemented", is addressed by this PR
and unique to expm. The second one seems to be common to some algebraic
jax.scipy.linalg functions, including expm and sqrtm, which says

```
OSError: /tmp/funcb63p6a7m/func.so: undefined symbol: blas_dtrsm
```

The undefined symbol is different for different functions. e.g. for
```sqrtm``` this undefined symbol is ```lapack_zgees```. Since this
really is a separate bug, I will open another issue and PR once I
investigate further what's going on. For this reason also, the batching
rule PR's test will need to marked as xfail for now, and back to success
once this second bug is fixed


**Related GitHub Issues:** closes #628 

[sc-62434]