Fixing catalyst measure error message (#2105)
**Context:** When using mid circuit measurements `catalyst.measure()`
and passing its value into a measurement process under the
single-branch-statistics mode, it fails with a low level error
concerning LLVM translation, which is not helpful to the user.

```
import catalyst
import pennylane as qml

@qml.qjit
@qml.set_shots(10)
@qml.qnode(qml.device("lightning.qubit", wires=2))
def c():
    qml.H(0)
    m = catalyst.measure(0)
    return qml.expval(m)

c()
```
Running the above program gives the following error.
```
CompileError: catalyst failed with error code 1: Compilation failed:
c:27:12: error: LLVM Translation failed for operation: builtin.unrealized_conversion_cast
      %9 = "quantum.compbasis"(%8) {operandSegmentSizes = array<i32: 0, 1>} : (!quantum.reg) -> !quantum.obs
           ^
c:27:12: note: see current operation: %20 = "builtin.unrealized_conversion_cast"() : () -> i64
Failed to translate LLVM module
```

**Description of the Change:**
Added some validation checks earlier to capture and raise the
appropriate error during the tracing stage.

**Benefits:** A more informative error message to let users know the
cause of failure.

[[sc-97982]]