Raise better error message when shots are required (#786)
The current situation is an error is raised from within JAX:
```
TypeError: Shapes must be 1D sequences of integer scalars, got (None, 1)
```