Cast result of measure_p back to int during plxpr interpreting (#2582)
**Context:**
The plxpr measure primitive returns an int type, but the catalyst
meaure_p primitive returns a bool type.

When interpreting the plxpr (to convert to catalyst jaxpr), the result
of `measure_p.bind()` is therefore a bool type, but the plxpr being
interpreted would expect the replacement equation for the plxpr measure
equation to also return an int type!

This was never exposed by our tests, and we encountered it when we tried
to use a mcm result as a conditional predicate. When users explicitly
request
```python
m = qml.measure(0)
if m == 0:
   ...
```

The arithmetic comparisons from the input plxpr are all on int types.
The plxpr for the above scenario looks like
```
          h:i64[] = measure[postselect=None reset=False] 0:i64[]
          i:bool[] = eq h 0:i64[]
          cond[
            # ... cond body ...
          ] i
```  

The `eq` equation is a comparison between int types, as that's what the
plxpr measure primitive returns. The binded catalyst measure_p returns a
bool, which is not accepted by the `eq` equation (which stays unchanged
and still expects an int: the plxpr conversion interpreter doesn't have
any interpretation rules for classical primitives), leading to an error
like

```
TypeError: lax.eq requires arguments to have the same dtypes, got bool, int64. (Tip: jnp.equal is a similar function that does automatic type promotion on inputs).
```

**Description of the Change:**
When interpreting plxpr's measurement primitive, after binding the
catalyst measure primitive (which returns bool), cast the result to int
type.

**Benefits:**
Types match: during interpretation, the new equation (catalyst measure)
and the replaced equation (plxpr measure) must return the same types.


**Related GitHub Issues:**
closes #2579 
[sc-113905], [sc-112370]