Implement one shot mcm as an mlir pass (#2458)
**Context:**
The current way catalyst handles the one shot mcm method is to perform a
tape-level transform at the python level.
This is problematic in two ways:
1. It is very messy and has many limitations
2. It is not compatible with capture

**Description of the Change:**
Implement one shot mcm as an mlir pass.

For the various MPs, here are their one-shot logic:
- [x] State: not supported, since it is only meaningful in analytical
mode
- [x] Var: only supported on MCMs. The 1-shot var is always zero, so we
need to calculate var from samples, but we do not have the ability to
sample a named observable yet in catalyst
- [x] Expval and probs: add up results from the single shot executions
and divide by the number of shots
- [x] Sample: Concatenate individual shot's samples together
- [x] Counts: Add the counts from each shot

When the returned MP is on MCMs, the one-shot kernel needs some
massaging as well:
- [x] Expval: expval on a single-shot mcm is just that mcm itself
- [x] Probs: each shot returns either [1,0] or [0,1], depending on the
mcm result
- [x] Sample: each shot returns 0 or 1, i.e. the mcm itself
- [x] Coutns: each shot returns [0,1] as eigvals, and [1,0] or [0,1] as
the mcm result. However, counts on mcm in plxpr path is currently
blocked by
```
NotImplementedError: CountsMP returns a dictionary, which is not compatible with capture
```
Resolved in https://github.com/PennyLaneAI/pennylane/pull/9022

**Benefits:**
No longer need to do the one shot transform in legacy frontend, so
one-shot will be capture compatible.
As a standalone mlir pass, we can also simplify its logic significantly,
since it no longer has to deal with the jax-generated army of
unnecessary stablehlo ops from python.

**Possible Drawbacks:**
Since this is a new implementation, we might lose some feature from what
is currently supported in legacy frontend's one-shot implementation.
However, I'm not super concerned here, as the legacy frontend's one-shot
implementation already feels quite random and clunky in what features it
supports.

**Related GitHub Issues:**
[sc-109620]