Revert openblas linking changes from #451 (#1386)
PR #451 introduced linking against both OpenBLAS and LAPACKE+Accelerate
on arm macOS, which breaks re-compilation of certain user programs (like
Shor's). The cause of the shared library conflict is unknown.

For now, we revert these linking changes, which were originally
introduced due to Lightning not finding its OpenBLAS dependency when
invoked through Catalyst:
```
FAILED frontend/test/pytest/test_measurements_shots_results.py::TestExpval::test_hermitian[lightning.qubit]

RuntimeError: [pennylane_lightning/core/src/utils/SharedLibLoader.hpp][Line:60][Method:SharedLibLoader]: Error in PennyLane Lightning: dlopen(libscipy_openblas.dylib, 0x0001): tried: 'libscipy_openblas.dylib' (no such file), '$ORIGIN/../scipy_openblas32/lib/libscipy_openblas.dylib' (no such file)
```

The above test will fail as a result of this, which we plan to fix with
a PR on the lightning side.

[sc-80803]