Revert "Remove restriction on the number of jobs for the Linux Arm64 workflow" (#1000)
We've been observing CI runs where the compiler gets killed `c++: fatal
error: Killed signal terminated program cc1plus`. I suspect this is due
to the runner running out of memory, so we reinstate the restriction on
the number of parallel runners for Linux arm builds.

Reverts PennyLaneAI/catalyst#992