Fixing qml demo one shot issue (#2056)
**Context:** The recent one-shot implementaiton in Catalyst is causing a
build
[failure](https://github.com/PennyLaneAI/qml/actions/runs/17844479263/job/50741097686)
in the QML demo repository, giving the error:

```
      ...

      File "/home/runner/work/qml/qml/.venv-build/lib/python3.11/site-packages/catalyst/qfunc.py", line 292, in __call__
        fn_result = configure_mcm_and_try_one_shot(self, args, kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/qml/qml/.venv-build/lib/python3.11/site-packages/catalyst/qfunc.py", line 173, in configure_mcm_and_try_one_shot
        return Function(dynamic_one_shot(qnode, mcm_config=mcm_config))(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ...

      File "/home/runner/work/qml/qml/.venv-build/lib/python3.11/site-packages/catalyst/qfunc.py", line 334, in __call__
        flattened_fun, _, _, out_tree_promise = deduce_avals(
                                                ^^^^^^^^^^^^^
      File "/home/runner/work/qml/qml/.venv-build/lib/python3.11/site-packages/catalyst/jax_extras/tracing.py", line 401, in deduce_avals
        verify_static_argnums_type(static_argnums)
      File "/home/runner/work/qml/qml/.venv-build/lib/python3.11/site-packages/catalyst/tracing/type_signatures.py", line 101, in verify_static_argnums_type
        raise TypeError(
    TypeError: The `static_argnums` argument to `qjit` must be an int or convertable to atuple of ints, but got value (Traced<~int64[]>with<DynamicJaxprTrace>,)
```

As a side note, the failure comes from the checks
in`frontend/catalyst/tracing/type_signatures.py`.
```python
def verify_static_argnums_type(static_argnums):
    """Verify that static_argnums have correct type.

    Args:
        static_argnums (Iterable[int]): indices to verify

    Returns:
        None
    """
    is_tuple = isinstance(static_argnums, tuple)
    is_valid = is_tuple and all(isinstance(arg, int) for arg in static_argnums)
    if not is_valid:
        raise TypeError(
            "The `static_argnums` argument to `qjit` must be an int or convertable to a"
            f"tuple of ints, but got value {static_argnums}"
        )
    return None
```
When we ignore the verification, the aforementioned issue will be
resolved as well. However, it doesn't make sense to remove this check as
a solution, as it may lead to more issues down the line.

**Description of the Change:** We solve this by passing `static_argnums`
correctly to internally transformed kernel functions,
which includes the one-shot mid circuit measurement transform here.

**Benefits:** Resolve the build failure in the QML repo.

---------

Co-authored-by: paul0403 <paulhaochen.wang@gmail.com>