Fix dialects build when using libstdc++ 14 from gcc (#3138)
**Context:**
Fix dialects build with libstdc++ 14 headers

The follwing pattern fails when using clang with the libstdc++ 14
headers:
```
llvm::enumerate(llvm::reverse(mcmobs.getMcms()))
```
with this error:

```
    error: no matching constructor for initialization of
      'indexed_accessor_range_base<mlir::OperandRange, ...>::iterator'
```

This is a know issue of std::reverse_iterator` over libstdc++ 14 . The
error shows up on Ubuntu 24.04 whenever the gcc-14 headers are
installed.

**Description of the Change:**

Copies the operands into a `SmallVector<Value>` before reversing, so the
reversed iterator is a plain `Value *`

**Description of the Change:**

**Benefits:**
`make dialects` builds on Ubuntu 24.04 with the gcc-14 headers present.

**Possible Drawbacks:**

**Related GitHub Issues:**