Raising build errors if cargo is required and not found (#393)
The runtime requires an installation of `cargo` to build `qir-stdlib`
from source (on macOS or by developer requires via the
`BUILD_QIR_STDLIB_FROM_SRC=ON` CMake flag). Currently, if the developer
forget to install cargo or the llvm rustup component, the build will be
failed with the following error message:

``` console
catalyst/runtime/include/RuntimeCAPI.h:21:10: fatal error: 'qir_stdlib.h' file not found
#include "qir_stdlib.h"
```

This PR updates the build system of the runtime to throw errors at the
proper build step with a clear message:

``` console
-- Building qir-stdlib from source.
CMake Error at CMakeLists.txt:74 (message):
  Missing cargo installation

  Please install "Rust" and the "llvm-tools-preview" rustup component for
  building qir-stdlib from source.  See the installation guideline for
  details:
  https://docs.pennylane.ai/projects/catalyst/en/stable/dev/installation.html
```